CREATE TABLE bookGenres (
  bookID INT NOT NULL,
  genreID INT NOT NULL,
  FOREIGN KEY (bookID) REFERENCES books (ID) ON DELETE CASCADE,
  FOREIGN KEY (genreID) REFERENCES genres (ID) ON DELETE CASCADE,
  PRIMARY KEY (bookID, genreID)
);
